apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-local
  namespace: argocd
spec:
  project: finops-platform
  source:
    repoURL: https://github.com/pershinaM/kubernetes-finops-platform.git
    targetRevision: HEAD
    path: platform/local
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
