apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd.yaml
  - finops-system.yaml
  - observability.yaml
  - governance-system.yaml
  - dev.yaml
  - stage.yaml
  - prod.yaml
