apiVersion: v1
kind: Service
metadata:
  name: checkout
  labels:
    app.kubernetes.io/name: checkout
    app.kubernetes.io/component: api
    finops.openai.io/product: commerce
    finops.openai.io/team: payments
    finops.openai.io/environment: prod
    finops.openai.io/component: application
spec:
  selector:
    app.kubernetes.io/name: checkout
  ports:
    - name: http
      port: 80
      targetPort: 5678
