apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  labels:
    app.kubernetes.io/name: analytics
    app.kubernetes.io/component: api
    finops.openai.io/product: insights
    finops.openai.io/team: data-platform
    finops.openai.io/environment: stage
    finops.openai.io/component: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: analytics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: analytics
        app.kubernetes.io/component: api
        finops.openai.io/product: insights
        finops.openai.io/team: data-platform
        finops.openai.io/environment: stage
        finops.openai.io/component: application
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5678"
    spec:
      containers:
        - name: analytics
          image: hashicorp/http-echo:1.0.0
          args:
            - -text=analytics
            - -listen=:5678
          ports:
            - containerPort: 5678
              name: http
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 700m
              memory: 768Mi
